// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `au-mcp-core`.

import type { McpHook, McpTool } from '@arsumbris/au-mcp-sdk/generated'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface McpHookInstanceCountNotice extends Omit<McpHook, 'type'> {
  type: 'mcp.hook.instance-count-notice'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  forType: DefRef<string>
  /** Refined Number, >= 0, integer */
  threshold: number
  message?: string
}

export interface McpHookNativeToolRedirect extends Omit<McpHook, 'type'> {
  type: 'mcp.hook.nativeToolRedirect'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpHookReadGuard extends Omit<McpHook, 'type'> {
  type: 'mcp.hook.read-guard'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpHookRepoOverview extends Omit<McpHook, 'type'> {
  type: 'mcp.hook.repo-overview'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpHookRequiredScopeCheck extends Omit<McpHook, 'type'> {
  type: 'mcp.hook.requiredScope-check'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpHookToolPrecondition extends Omit<McpHook, 'type'> {
  type: 'mcp.hook.tool-precondition'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpToolAssignBlockId extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.assign_block_id'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the file holding the entity to address. */
  file_path: string
  /**
   * a byte offset (from a wire-served span) inside the inline record / markdown block to assign a `^:` id to.
   * Refined Number, >= 0, integer
   */
  at: number
}

export interface McpToolAuAnchors extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_anchors'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the wikilink target whose headings to list, e.g. "note" or "note::repo". */
  target: string
  /** absolute path of the file the link would appear in (scopes a bare target repo-local). Optional. */
  origin?: string
}

export interface McpToolAuBlockIds extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_block_ids'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the wikilink target whose block ids to list, e.g. "note" or "note::repo". */
  target: string
  /** absolute path of the file the link would appear in (scopes a bare target repo-local). Optional. */
  origin?: string
}

export interface McpToolAuCandidates extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_candidates'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * page size (default 50).
   * Refined Number, >= 1, integer
   */
  limit?: number
  /**
   * skip this many candidate files before the page (use the returned next_offset).
   * Refined Number, >= 0, integer
   */
  offset?: number
}

export interface McpToolAuChildren extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_children'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the directory whose direct entries to list. */
  dir: string
}

export interface McpToolAuDiagnostics extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_diagnostics'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** filter to diagnostics on exactly this file (absolute path). */
  path?: string
  /** filter to diagnostics under this directory prefix (absolute path). */
  path_prefix?: string
  /** filter by severity tier; the page defaults to "error" when omitted. */
  severity?: 'error' | 'drift' | 'warning' | 'hint'
  /** filter by diagnostic code (the engine owns ~80 codes; String so it never goes stale here). */
  code?: string
  /**
   * page size (default 50).
   * Refined Number, >= 1, integer
   */
  limit?: number
  /**
   * skip this many entries before the page (a short page means done).
   * Refined Number, >= 0, integer
   */
  offset?: number
}

export interface McpToolAuFiles extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_files'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** only this member's files. Absent spans every mounted member. */
  repo?: string
  /** "all" (DEFAULT — a wikilink into a dependency is legal) or "own" (your own repos). */
  scope?: 'all' | 'own'
  /**
   * page size.
   * Refined Number, >= 1, integer
   */
  limit?: number
  /**
   * page offset.
   * Refined Number, >= 0, integer
   */
  offset?: number
}

export interface McpToolAuFollow extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_follow'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the wikilink to follow, e.g. "note", "note::repo", "note#Heading", "note^blk", "note^^blk". */
  target: string
  /** absolute path of the file the link appears in (REQUIRED; scopes a bare target repo-local, a ::repo target cross-repo). */
  origin: string
}

export interface McpToolAuFrontmatter extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_frontmatter'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path whose frontmatter to parse and return as JSON. */
  path: string
}

export interface McpToolAuHostIntentFire extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_host_intent_fire'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the intent type name to fire (from au_host_intent_list); routing is stamped from the type graph, you don't supply it. */
  intent: string
  /** the intent's fields as a JSON object, e.g. {target: {...}, mode: transient} — see au_host_intent_list for the shape. */
  payload?: unknown
}

export interface McpToolAuHostIntentList extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_host_intent_list'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpToolAuHostPaneOp extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_host_pane_op'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the layout verb — today only "activate" (reveal/focus a pane); future verbs ride this same tool. */
  op: string
  /** the target pane id (from au_host_snapshot's node ids); required by verbs that target a pane. */
  paneId?: string
}

export interface McpToolAuHostSnapshot extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_host_snapshot'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpToolAuHubs extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_hubs'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** scope to one repo; omit for the default (own-scoped) answer. */
  repo?: string
  /** 'own' (default) = your own repos only; 'all' = every mounted repo. */
  scope?: string
  /**
   * page size; omit for the engine's top-N (the bound overview.hubs carries).
   * Refined Number, >= 1, integer
   */
  limit?: number
  /**
   * page offset into the ranking; omit to start at the top.
   * Refined Number, >= 0, integer
   */
  offset?: number
}

export interface McpToolAuInstances extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_instances'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** return each instance's full introspection (effective_shape, collisions, values, body_events) — heavy; prefer au_resolved {path} for one. */
  detail?: boolean
  /**
   * page size (default 100).
   * Refined Number, >= 1, integer
   */
  limit?: number
  /**
   * skip this many instances before the page.
   * Refined Number, >= 0, integer
   */
  offset?: number
}

export interface McpToolAuInstancesOf extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_instances_of'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the type name to list instances of (bare matches every same-named identity across repos; name::repo picks one owner). */
  ofType: string
  /** restrict which origins count — any of "file" (whole files) / "nested" (inline records) / "meta" (type-def meta); omit for all. */
  origins?: Array<'file' | 'nested' | 'meta'>
  /** return each instance's full resolved fields (heavy — avoid for large/append-only types). */
  resolve?: boolean
  /**
   * page size (default 100).
   * Refined Number, >= 1, integer
   */
  limit?: number
  /**
   * skip this many instances before the page.
   * Refined Number, >= 0, integer
   */
  offset?: number
}

export interface McpToolAuListImports extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_list_imports'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpToolAuMembers extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_members'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpToolAuNeighborhood extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_neighborhood'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the file to SEED the walk at. */
  path: string
  /** which way to walk — "out" (outgoing refs, the default), "in" (backlinks), or "both" (per-hop, either direction). */
  direction?: 'out' | 'in' | 'both'
  /**
   * how many hops out from the seed. 0 or absent = the seed node only.
   * Refined Number, >= 0, integer
   */
  depth?: number
  /** which reference edge kinds to follow. REQUIRED past depth 1 (an unfiltered deep walk explodes through hubs). */
  kinds?: Array<'field-reference' | 'field-string-wikilink' | 'contributing' | 'navigational'>
  /** scope — "all" (every mounted repo, the default) or "own" (only the editable authoring surfaces). */
  scope?: 'own' | 'all'
  /**
   * cap the node count; the result reports truncation loudly rather than dropping silently.
   * Refined Number, >= 1, integer
   */
  max_nodes?: number
  /** splice each node's whole-file content (frontmatter included) onto the result. */
  content?: boolean
  /** splice each node's prose body (frontmatter stripped) onto the result. */
  body?: boolean
  /** splice each node's resolved typed-instance view (null for a plain note). */
  instance?: boolean
}

export interface McpToolAuOverview extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_overview'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** scope to one repo; omit for the default (own-scoped) answer. */
  repo?: string
  /** 'own' (default) = your own repos only; 'all' = every mounted repo. */
  scope?: string
}

export interface McpToolAuReferences extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_references'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the file whose wikilink references to return. */
  path: string
  /** direction — "out" (outgoing links) or "in" (backlinks). */
  which: 'out' | 'in'
}

export interface McpToolAuResolveMember extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_resolve_member'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path; returns { repo, root, editable, local, role } of the declared member that owns it, or null. */
  path: string
}

export interface McpToolAuResolved extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_resolved'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the typed instance to resolve (field values, provenance, refs); null on a non-instance. */
  path: string
}

export interface McpToolAuSemanticTokens extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_semantic_tokens'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path whose typed highlight-token stream to return (null for a non-held file). */
  path: string
}

export interface McpToolAuSubtypes extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_subtypes'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the base type; returns every type-def whose closure includes it (descend a schema tree). */
  base: string
}

export interface McpToolAuTopLevelDirs extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_top_level_dirs'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** scope to one repo's dirs; omit for the default (own-scoped) answer. */
  repo?: string
  /** 'own' (default) = your own repos only; 'all' = every mounted repo (the old workspace-wide answer). */
  scope?: string
}

export interface McpToolAuType extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_type'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the type-def name to fetch (returns the WireTypeDef, or null if absent). */
  name: string
  /** disambiguate a borrowed copy by owner repo. */
  repo?: string
}

export interface McpToolAuTypeSystem extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_type_system'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** one atom name to fetch (or the diagnostic-codes catalog); omit for the map (moc + atom names). */
  name?: string
  /** fetch the WHOLE reference bundle (moc + every atom except the diagnostic-codes catalog) in one call — large. */
  full?: boolean
}

export interface McpToolAuTypeTree extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_type_tree'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpToolAuTyped extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_typed'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path to classify (typed instance / type-def / plain note). */
  path: string
}

export interface McpToolAuTypes extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_types'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** scope to one repo's type-defs; omit for the whole workspace. */
  repo?: string
  /** return the FULL WireTypeDef per type instead of a light summary row (heavy — prefer scoping/paging). */
  detail?: boolean
  /**
   * page size (default 50).
   * Refined Number, >= 1, integer
   */
  limit?: number
  /**
   * skip this many types before the page (use the returned next_offset).
   * Refined Number, >= 0, integer
   */
  offset?: number
}

export interface McpToolAuValidate extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.au_validate'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the type name to validate against. */
  typeName: string
  /** the candidate record as a JSON OBJECT / mapping (e.g. {common-name: Oak, type: plant}), NOT a string. */
  value: unknown
  /** disambiguate the type by owner repo. */
  repo?: string
}

export interface McpToolBash extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.bash'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the shell command you would run (recorded as a demand signal — bash does not execute yet). */
  command: string
  /**
   * intended timeout in ms (recorded; not enforced while bash is unavailable).
   * Refined Number, >= 0, integer
   */
  timeout?: number
}

export interface McpToolDeleteFile extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.delete_file'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the file to remove. */
  file_path: string
  /** read-before-write guard — the file's current hash; a mismatch rejects without deleting. */
  expected_hash?: string
}

export interface McpToolEditFile extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.edit_file'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path to the file to edit. */
  file_path: string
  /** the exact text to replace; must match verbatim and be unique unless replace_all. */
  old_string: string
  /** the replacement text. */
  new_string: string
  /** replace every occurrence instead of requiring old_string to be unique. */
  replace_all?: boolean
}

export interface McpToolGlob extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.glob'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the glob to match file paths against, e.g. "**\/*.ts". */
  pattern: string
  /** absolute directory to search under; omit to search the whole workspace. */
  path?: string
}

export interface McpToolGrepFiles extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.grep_files'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the regex to search file contents for (JS RegExp syntax). */
  query: string
  /** absolute directory to search under; omit to search the whole workspace. */
  path?: string
  /** a glob restricting which files are searched, e.g. "**\/*.ts"; omit to search all. */
  glob?: string
  /** match case-sensitively; default is case-insensitive. */
  case_sensitive?: boolean
  /** output mode — "content" (default: path:line:match), "files" (matching paths only), "count" (path:count per file). */
  mode?: string
  /**
   * page size — max results returned (default 500). Pair with offset to page through a large result set.
   * Refined Number, >= 1, integer
   */
  limit?: number
  /**
   * skip this many results before the page (default 0); the footer reports the next offset when more remain.
   * Refined Number, >= 0, integer
   */
  offset?: number
  /**
   * truncate each match line to this many chars in "content" mode (default 300); stops one very long line overflowing the token cap.
   * Refined Number, >= 1, integer
   */
  max_line_length?: number
}

export interface McpToolInline extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.inline'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the file to fold in + DELETE (must have no non-empty body). */
  file_path: string
  /** absolute path of the HOST file to fold file_path into as an inline `^:` record. */
  into: string
  /**
   * a byte offset in `into` landing on the [[file_path]] reference; required only when `into` references file_path more than once.
   * Refined Number, >= 0, integer
   */
  at?: number
}

export interface McpToolPromote extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.promote'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the HOST file holding the inline record to extract. */
  file_path: string
  /** absolute path of the new file to extract into (.md/.markdown/.yaml/.yml); a [[to]] reference is left behind. */
  to: string
  /**
   * locate the record by byte offset (for a record without a `^:` id); pass EXACTLY ONE of at / block_id.
   * Refined Number, >= 0, integer
   */
  at?: number
  /** locate the record by its `^:` id; pass EXACTLY ONE of at / block_id. */
  block_id?: string
}

export interface McpToolReadFilePinned extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.read_file_pinned'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the file to read. */
  file_path: string
  /**
   * 1-based line to start from; omit to read from the top.
   * Refined Number, >= 0, integer
   */
  offset?: number
  /**
   * max number of lines to read from offset; omit to read to the end.
   * Refined Number, >= 1, integer
   */
  limit?: number
}

export interface McpToolRename extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.rename'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the file to move (not a type-def file — use rename_type). */
  file_path: string
  /** absolute destination path (same repo); every inbound reference is rewritten to follow. */
  to: string
}

export interface McpToolRenameBlockId extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.rename_block_id'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path of the host file holding the inline `^:` record. */
  file_path: string
  /** the record's current block-id (inline `^:` records only; a body-marker ^id rejects). */
  block_id: string
  /** the new block-id (must be free in the host's id namespace); every filtered referrer is rewritten. */
  to_block_id: string
}

export interface McpToolRenameType extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.rename_type'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the type-def's current name (bare, or ::repo-qualified to pick an owner) — a TYPE NAME, not a path. */
  old_name: string
  /** the owner's new type name (bare); the def file + both reference surfaces cascade. */
  new_name: string
}

export interface McpToolWriteFile extends Omit<McpTool, 'type'> {
  type: 'mcp.tool.write_file'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** absolute path to write; parent dirs are created. */
  file_path: string
  /** the full file contents (overwrites any existing file). */
  content: string
}
